// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDow0IATQf03MKogmDLHz6qdarHzXvWWEE',
    appId: '1:74878827502:web:1ace8f880ba6817da9ecff',
    messagingSenderId: '74878827502',
    projectId: 'gemstore-5f5a8',
    authDomain: 'gemstore-5f5a8.firebaseapp.com',
    storageBucket: 'gemstore-5f5a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwP-JFp39t57kMZ0FcuBRKKgTGXbPDQl4',
    appId: '1:74878827502:android:2d98979f9bf13b78a9ecff',
    messagingSenderId: '74878827502',
    projectId: 'gemstore-5f5a8',
    storageBucket: 'gemstore-5f5a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD4Zv8NW9piAHcZqgHdA2iXMJ-k8fih7k',
    appId: '1:74878827502:ios:5ccec0a6c7d4cd75a9ecff',
    messagingSenderId: '74878827502',
    projectId: 'gemstore-5f5a8',
    storageBucket: 'gemstore-5f5a8.appspot.com',
    iosBundleId: 'com.example.gemshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD4Zv8NW9piAHcZqgHdA2iXMJ-k8fih7k',
    appId: '1:74878827502:ios:a8db70cc17ebadf4a9ecff',
    messagingSenderId: '74878827502',
    projectId: 'gemstore-5f5a8',
    storageBucket: 'gemstore-5f5a8.appspot.com',
    iosBundleId: 'com.example.gemshop.RunnerTests',
  );
}
